name: stack-os-matrix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [ labeled, review_requested ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-centos:
    runs-on: ubuntu-latest
    if: contains(github.event.labels.*.name, 'CI')
    container:
      image: centos:8
      env:
        GITHUB_WORKSPACE: /workspace
      volumes:
        - ${{ github.workspace }}:/workspace
    steps:
      - name: Deploy and build
        run: |
          echo hi
  build-macos:
    runs-on: macos-latest
    if: contains(github.event.labels.*.name, 'CI')
    steps:
      - name: Deploy and build
        run: |
          echo hi
    
        
