name: stack-os-matrix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [ labeled, review_requested ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-centos8:
    runs-on: ubuntu-latest
    container:
      image: centos:8
      env:
        GITHUB_WORKSPACE: /workspace
      volumes:
        - ${{ github.workspace }}:/workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy and build
        run: |
          pwd
          ls
          echo $GITHUB_WORKSPACE
          ls /workspace
          echo '${{ github.event }}'
  build-centos7:
    runs-on: ubuntu-latest
    container:
      image: centos:7
      env:
        GITHUB_WORKSPACE: /workspace
      volumes:
        - ${{ github.workspace }}:/workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy and build
        run: |
          pwd
          ls
          echo $GITHUB_WORKSPACE
          ls /workspace
          echo '${{ github.event }}'
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy and build
        run: |
          pwd
          ls
          echo $GiTHUB_WORKSPACE
          echo '${{ github.event.pull_request }}'
